In [1]:
import pandas as pd

df = pd.read_csv('C:/Users/Patrick/Desktop/Masterarbeit/Code_Patrick/AI-CPS-Masterarbeit-Patrick/code/taskManager/power_logs_green/2025-05-21 15-52-50_power-log-random_18.csv')

df.head(30)

,client_id,total_power_usage,kwh,relevant_power_values,num_of_power_values,tasks_assigned,efficiency_per_task,efficiency,total_duration,time_per_task,avg_power
0,764045,382.258092,0.000106,"[41.4, 41.4, 41.4, 26.1, 26.1, 41.9, 41.9, 28....",24,1,0.000106,9417.720839,11.734707,11.734707,32.575000
1,835230,6088.617033,0.001691,"[88.0, 88.0, 88.0, 100.2, 100.2, 90.4, 90.4, 7...",58,5,0.000338,2956.336374,54.369348,10.873870,111.986207
2,0,6470.875125,0.001797,NaN,82,6,0.000222,6187.028607,33.052028,11.304288,3235.437562
3,764045,343.307218,0.000095,"[32.4, 32.4, 35.2, 35.2, 35.2, 29.4, 29.4, 29....",19,2,0.000048,20972.469039,10.824489,5.412245,31.715789
4,835230,4735.449149,0.001315,"[148.9, 148.9, 142.1, 139.9, 139.9, 132.2, 132...",31,4,0.000329,3040.894231,34.557185,8.639296,137.032258
5,0,5078.756367,0.001411,NaN,50,6,0.000188,12006.681635,22.690837,7.025770,2539.378184
6,764045,433.950216,0.000121,"[17.6, 17.6, 34.9, 34.9, 34.9, 30.6, 30.6, 30....",28,3,0.000040,24887.647457,14.048568,4.682856,30.889286
7,835230,3443.747225,0.000957,"[139.9, 139.9, 143.4, 130.1, 130.1, 130.1, 141...",20,3,0.000319,3136.118680,25.288201,8.429400,136.180000
8,0,3877.697441,0.001077,NaN,48,6,0.000180,14011.883068,19.668384,6.556128,1938.848721

In [3]:
df_2 = pd.read_csv('C:/Users/Patrick/Desktop/Masterarbeit/Code_Patrick/AI-CPS-Masterarbeit-Patrick/code/taskManager/power_logs_green/2025-05-24 20-26-33_power-log-random_4.csv')

df_2.head(30)

,round,client_id,scenario,total_power_usage,kwh,relevant_power_values,num_of_power_values,tasks_assigned,efficiency_per_task,efficiency,total_duration,time_per_task,avg_power
0,NaN,835230,NaN,2756.174980,0.000766,"[90.0, 90.0, 94.4, 86.9, 78.7, 78.7, 79.7, 103...",32,2,0.000383,2612.316000,24.513633,12.256816,112.434375
1,NaN,0,NaN,2756.174980,0.000766,NaN,32,2,0.000383,2612.316000,24.513633,12.256816,2756.174980
2,NaN,835230,NaN,2594.542594,0.000721,"[147.7, 147.7, 147.7, 131.1, 131.1, 131.3, 141...",12,2,0.000360,2775.055617,18.748953,9.374476,138.383333
3,NaN,0,NaN,2594.542594,0.000721,NaN,12,2,0.000360,2775.055617,18.748953,9.374476,2594.542594

In [5]:

df_3 = pd.read_csv('C:/Users/Patrick/Desktop/Masterarbeit/Code_Patrick/AI-CPS-Masterarbeit-Patrick/code/taskManager/power_logs_green/2025-05-24 22-27-53_power-log-random_4.csv')

df_3.head(30)

,round,client_id,scenario,total_power_usage,kwh,relevant_power_values,num_of_power_values,tasks_assigned,efficiency_per_task,efficiency,total_duration,time_per_task,avg_power
0,1.0,835230,apply,1444.049412,0.000401,"[85.7, 85.7, 100.2, 100.2, 100.2, 87.3, 87.3, ...",16,1,0.000401,2492.989486,15.398061,15.398061,93.781250
1,1.0,835230,apply,2443.262101,0.000679,"[85.7, 85.7, 100.2, 100.2, 100.2, 87.3, 87.3, ...",29,1,0.000679,1473.439955,24.545190,24.545190,99.541379
2,NaN,0,NaN,2443.262101,0.000679,NaN,29,1,0.000679,1473.439955,24.545190,24.545190,2443.262101
3,2.0,835230,apply,1204.250464,0.000335,"[129.0, 129.0, 129.0, 119.9, 119.9, 119.9, 130...",9,1,0.000335,2989.411346,9.553331,9.553331,126.055556
4,2.0,835230,apply,2521.668487,0.000700,"[129.0, 129.0, 129.0, 119.9, 119.9, 119.9, 130...",20,1,0.000700,1427.626200,19.066716,19.066716,132.255000
5,NaN,0,NaN,2521.668487,0.000700,NaN,20,1,0.000700,1427.626200,19.066716,19.066716,2521.668487

In [ ]:
df_4 = pd.read_csv('C:/Users/Patrick/Desktop/Masterarbeit/Code_Patrick/AI-CPS-Masterarbeit-Patrick/code/taskManager/power_logs_green/2025-05-24 22-32-25_power-log-random_6.csv')

df_4.head(30)

,round,client_id,scenario,total_power_usage,kwh,relevant_power_values,num_of_power_values,tasks_assigned,efficiency_per_task,efficiency,total_duration,time_per_task,avg_power
0,1.0,835230,apply,1420.608174,0.000395,"[75.7, 75.7, 95.3, 95.3, 92.1, 80.0, 80.0, 80....",16,1,0.000395,2534.125923,15.205868,15.205868,93.425000
1,1.0,835230,apply,2431.216250,0.000675,"[75.7, 75.7, 95.3, 95.3, 92.1, 80.0, 80.0, 80....",30,1,0.000675,1480.740350,24.092121,24.092121,100.913333
2,NaN,0,NaN,2431.216250,0.000675,NaN,30,1,0.000675,1480.740350,24.092121,24.092121,2431.216250
3,2.0,835230,apply,1166.016039,0.000324,"[114.7, 114.7, 135.1, 135.1, 132.5, 117.8, 117...",11,1,0.000324,3087.436089,9.276182,9.276182,125.700000
4,2.0,835230,apply,2566.120854,0.000713,"[114.7, 114.7, 135.1, 135.1, 132.5, 117.8, 117...",21,1,0.000713,1402.895735,19.099928,19.099928,134.352381
5,NaN,0,NaN,2566.120854,0.000713,NaN,21,1,0.000713,1402.895735,19.099928,19.099928,2566.120854
6,3.0,835230,apply,1256.604690,0.000349,"[126.3, 126.3, 145.9, 145.9, 145.9, 135.4, 135...",8,1,0.000349,2864.862775,9.189905,9.189905,136.737500
7,3.0,835230,apply,2524.409433,0.000701,"[126.3, 126.3, 145.9, 145.9, 145.9, 135.4, 135...",12,1,0.000701,1426.076116,18.360454,18.360454,137.491667
8,NaN,0,NaN,2524.409433,0.000701,NaN,12,1,0.000701,1426.076116,18.360454,18.360454,2524.409433